// <auto-generated />
using System;
using CarwashMonitor.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarwashMonitor.Migrations
{
    [DbContext(typeof(CarwashDbContext))]
    [Migration("20250812210336_AddCoinTrayAmountToBox")]
    partial class AddCoinTrayAmountToBox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarwashMonitor.Models.Box", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CoinTrayAmount")
                        .HasColumnType("integer");

                    b.Property<int>("CoinTrayLimit")
                        .HasColumnType("integer");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("Boxes");
                });

            modelBuilder.Entity("CarwashMonitor.Models.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("CarwashMonitor.Models.WashCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uuid");

                    b.Property<int?>("CoinAmount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float?>("DetergentConsumption")
                        .HasColumnType("real");

                    b.Property<float?>("WaterConsumption")
                        .HasColumnType("real");

                    b.Property<float?>("WaxConsumption")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("BoxId");

                    b.ToTable("WashCycles");
                });

            modelBuilder.Entity("CarwashMonitor.Models.Box", b =>
                {
                    b.HasOne("CarwashMonitor.Models.Station", "Station")
                        .WithMany("Boxes")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("CarwashMonitor.Models.WashCycle", b =>
                {
                    b.HasOne("CarwashMonitor.Models.Box", "Box")
                        .WithMany("WashCycles")
                        .HasForeignKey("BoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Box");
                });

            modelBuilder.Entity("CarwashMonitor.Models.Box", b =>
                {
                    b.Navigation("WashCycles");
                });

            modelBuilder.Entity("CarwashMonitor.Models.Station", b =>
                {
                    b.Navigation("Boxes");
                });
#pragma warning restore 612, 618
        }
    }
}
